# Generated by Django 3.0.5 on 2020-05-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('teacher', models.CharField(max_length=150, null=True)),
                ('room', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
