# Generated by Django 3.0.5 on 2020-05-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(choices=[('4', '8.30-10.00'), ('2', '10.10-11.40'), ('3', '11.50-13.20')], max_length=30, null=True),
        ),
    ]
