# Generated by Django 2.2.12 on 2020-05-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200517_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='deadlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadlines', models.DateTimeField()),
                ('name', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('subject', models.CharField(max_length=250, null=True)),
                ('teacher', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
