# Generated by Django 3.0.5 on 2020-06-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('course', models.CharField(max_length=50, null=True)),
                ('task', models.CharField(max_length=250, null=True)),
                ('teacher', models.CharField(max_length=150, null=True)),
                ('group', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
